### ISSUE TITLE
clicking loading more comments will make it be highlighted in gold 

### ISSUE THREAD

**Issue by Thunder33345** [easyfuckingpeasy/chrome-reddit-comment-highlights#21] opened 2018-11-02 07:59 UTC
maybe an option to exclude it when you click load more comments?
or will that complicates things

**Comment by aesy** [comment] 2018-11-02 22:03
Hey,

The expected behavior when  clicking ''load more comments' is for new comments to get highlighted and old, already seen, comments shouldn't be. Is that not what happens? Or do you not want any comments in that case to get highlighted?

**Comment by Thunder33345** [comment] 2018-11-03 15:00
ahh make sense
i was thinking of something like not highlighting on the first time the page load(like all comments on posted before the page first load dont get highlighted)
i dont really know if it's feasible or even possible to track seen comments without like seeing them(if that's the case feel free to close this)

**Comment by aesy** [comment] 2018-11-05 22:48
Sorry, I have a hard time understanding. Do you mean that when clicking 'load more comments' only comments that were posted after the user visited the page should be highlighted? If that's the case, I think that's a wontfix imho, because I don't think it's something people would expect, but I'm open to adding it as an option if I get enough feedback that tells me it's something users want. I''ll close the issue for now.

**Closed as completed by aesy** 2018-11-05 22:48 UTC
Labels: wontfix

**Comment by Thunder33345** [comment] 2018-11-06 09:05
fair enough, understood 
have an afterthought that might not be as good as it sounds in first thought
