### ISSUE TITLE
Seems to work only sporadically in the past week

### ISSUE THREAD

**Issue by jerryasher** [easyfuckingpeasy/chrome-reddit-comment-highlights#28] opened 2022-11-30 18:11 UTC
I am running 2.0.1 and it now seems to work only sporadically

Is there anything we can do to help diagnose it?

It's a shame, Your extension adds a ton of value to my reddit experience.

**Comment by Hannah-GBS** [comment] 2022-11-30 19:45
Not working for me at all now it seems.

**Comment by aesy** [comment] 2022-11-30 21:11
Thanks for reporting, yeah, a handful of people have said the same, and I've also noticed it sporadically not seeming to work. I will definitely look into it and publish a fix, but best case scenario for a fix will be on Friday.

For anyone experiencing this, please post which version of the add-on/extension you're using and which browser version.
And if you know your way around the browser developer tools, you can enable debug logs in the add-on/extension settings, and then visit a thread with the developer tools console window open. Log lines belonging to the add-on starts with `time=`. If any of those lines are red (`level=ERROR`), feel free to post all log lines here (and censor any thread ids). You could also enable error reporting, but be aware that visited thread id's will be included in the reports.

**Comment by aesy** [comment] 2022-12-04 21:38
Just to keep you updated, I'm pretty sure I know what the issue is. It has to do with the background script initializing asynchronously on wake up (essentially a race condition) and the browser behaving weirdly when registering listeners asynchronously (documentation says as much [[1]](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Background_scripts#add_listeners) [[2]](https://developer.chrome.com/docs/extensions/mv2/background_pages/#listeners)). I'll be publishing a new release next week, probably sooner rather than later.

**Comment by az48954** [comment] 2023-07-11 13:52
Hello, I'm using version 2.0.1 with Firefox 114.0.2 (64-bit). The add-on only works rarely, if at all. Was a fix ever figured out?

**Comment by aesy** [comment] 2024-07-01 23:07
> Just to keep you updated, I'm pretty sure I know what the issue is. It has to do with the background script initializing asynchronously on wake up (essentially a race condition) and the browser behaving weirdly when registering listeners asynchronously (documentation says as much [[1]](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Background_scripts#add_listeners) [[2]](https://developer.chrome.com/docs/extensions/mv2/background_pages/#listeners)). I'll be publishing a new release next week, probably sooner rather than later.

This has been fixed in version `3.0.0`. I'll close this issue for now but feel free to lmk if it still doesn't work for you.

**Closed as completed by aesy** 2024-07-01 23:07 UTC
Labels: bug
