### ISSUE TITLE
Highlights are lost when the browser is closed (Firefox)

### ISSUE THREAD

**Issue by N6MCA51593** [easyfuckingpeasy/chrome-reddit-comment-highlights#26] opened 2021-01-29 15:19 UTC
I've been having this issue for over a month I think. Closing the browser causes the highlights to be lost. No such problem in Google Chrome. I'm not using the redesign btw.

**Comment by aesy** [comment] 2021-01-29 23:46
Hi, am I understanding you correctly that comments that were previously highlighted are no longer highlighted if you restart the browser? This is expected since the highlights are unseen comments since your last visit, so reloading the page will clear them, and a restart will reload the page. This should be the case in Chrome as well, which makes me unsure whether I understand what you mean. Can you clarify?

**Comment by N6MCA51593** [comment] 2021-01-30 00:09
Sorry for not making myself clear, I meant to say that the new highlights that were supposed to be showing were not being displayed, as if the extension forgets about the threads it was tracking when I close the browser.  Every time I open the browser, the extension drops any of threads I've opened since the last restart.

**Comment by aesy** [comment] 2021-01-30 16:20
Ah gotcha, thanks! There seems to have been some [changes](https://blog.mozilla.org/addons/2020/07/09/changes-to-storage-sync-in-firefox-79/) made to the extension storages in Firefox 79. I suspect that the `QUOTA_BYTES_PER_ITEM`and `MAX_ITEMS` properties are no longer defined on the [storage](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/sync), but still are in chrome. These properties are not documented (pretty sure they used to be though), so I'm guessing it's not a bug in Firefox. I'll try to verify this later today or tomorrow, but in case I'm not able to reproduce it, would you be okay if I give you some commands to run in your browser in order for us to debug the extension?

**Comment by N6MCA51593** [comment] 2021-01-30 18:53
Sure, would be glad to help.

**Comment by aesy** [comment] 2021-01-30 22:39
I'm able to reproduce it and it's due to the reason I suspected, but I also tested it in Firefox 78 and saw the same issue so this might have always been a problem... which is unfortunate.

Anyway, this has now been fixed in 8ac76075a551563f99e91b629db1681b20f73303, and I have pushed a new release for review. I'll close the issue and ping you when it's up so that you can verify that it now works as you'd expect! Thanks for the help! :)

**Closed as completed** 2021-01-30 22:40 UTC
Labels: bug, firefox

**Comment by aesy** [comment] 2021-01-30 22:53
Actually, it was auto-approved and should be available already!

**Comment by N6MCA51593** [comment] 2021-01-30 23:36
Thanks for the quick fix, I will report back if it doesn't work properly.
